version: '3.1' # Use whatever version is appropriate

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin # Root password
      MYSQL_DATABASE: db         # Optional: Creates a database
      MYSQL_USER: admin                 # Optional: Creates a new user
      MYSQL_PASSWORD: admin     # Password for the new user
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin@12345
    volumes:
      - sql_data:/var/opt/mssql


volumes:
  my-db:
  sql_data: